FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Skopiuj pliki projektu i przywróć zależności
COPY *.csproj ./
RUN dotnet restore

COPY . ./
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish ./

# Expose port for the application
EXPOSE 80
EXPOSE 443

# Uruchom aplikację
ENTRYPOINT ["dotnet", "E-Wolontariat.dll"]
